### ISSUE TITLE
"New window" doesn't work for sli files

### ISSUE THREAD

**Issue by kees-jan** [SCROOM-plugin-cpp/SCROOM-plugin-cpp#10] opened 2020-06-28 14:31 UTC
**Testcase**
 * Open an 'sli' file
 * Choose File->New Window

**Expected result**
A new window appears showing the same sli file

**Actual result**
Scroom crashes

**Comment by ethoxx** [comment] 2020-06-29 16:16
I was unfortunately unable to reproduce this issue. However, indeed there were some strange things going on when opening a new window for an SLI file, these are fixed in #12 
It would be great if you could verify that this PR also fixes the issue you experienced.

**Comment by JoostvanPinxten** [comment] 2020-07-02 09:51
I have not found any issues after the integration of PR #12. I will close this one. If other issues pop up, we can reopen, or make a new issue.

**Closed by JoostvanPinxten** 2020-07-02 09:51 UTC

**Comment by kees-jan** [comment] 2020-07-08 13:37
I, too, cannot reproduce it any more with the latest version.
